#!/bin/sh
# flashforge_init.sh
# Automated Deployment Script for Iroh on Flashforge 3D Printers (ARMv7 embedded Linux)

USB_MOUNT="/mnt/usb"
MODE_FILE="$USB_MOUNT/mode.txt"
IROH_BIN="$USB_MOUNT/iroh"
IROH_KEY="$USB_MOUNT/iroh_key.priv"
IROH_PERSISTENT_DIR="/usr/data/iroh_farm"
START_APP_SCRIPT="/usr/data/apps/start_app.sh"
START_COMMAND="/usr/data/iroh_farm/iroh node start --config-path=/usr/data/iroh_farm/ &"

echo "[*] Starting Flashforge Iroh Deployment"

if [ ! -f "$IROH_BIN" ]; then
    echo "[!] Error: Iroh binary not found at $IROH_BIN"
    exit 1
fi

MODE="RAM"
if [ -f "$MODE_FILE" ]; then
    # Read the mode, stripping any trailing whitespace/newlines
    MODE=$(cat "$MODE_FILE" | tr -d '\r' | tr -d '\n' | tr '[:lower:]' '[:upper:]')
fi

apply_firewall() {
    echo "[*] Applying network isolation profile on wlan0..."

    # Flush existing rules to prevent duplicates across multiple deployments
    iptables -D OUTPUT -o wlan0 -j IROH_ISOLATION 2>/dev/null || true
    iptables -F IROH_ISOLATION 2>/dev/null || true
    iptables -X IROH_ISOLATION 2>/dev/null || true

    # Create a custom firewall chain for proactive network isolation
    iptables -N IROH_ISOLATION

    # 1. Whitelist universal private local blocks to allow local computers/slicers on the LAN to connect
    iptables -A IROH_ISOLATION -d 192.168.0.0/16 -j ACCEPT
    iptables -A IROH_ISOLATION -d 10.0.0.0/8 -j ACCEPT

    # 2. Allow outbound UDP for DNS (53) and Secure QUIC/DERP mapping (443) for Iroh hole-punching
    iptables -A IROH_ISOLATION -p udp --dport 53 -j ACCEPT
    iptables -A IROH_ISOLATION -p udp --dport 443 -j ACCEPT

    # 2b. Allow outbound TCP 443 (HTTPS) for the iroh relay handshake: relay
    # registration and peer introduction run over TLS. Without this the printer
    # can never be found across networks. All other TCP stays blocked.
    iptables -A IROH_ISOLATION -p tcp --dport 443 -j ACCEPT

    # 3. Block all remaining outbound TCP traffic globally (kills HTTP cloud connections & OTA pings)
    iptables -A IROH_ISOLATION -p tcp -j DROP

    # 4. Drop any remaining generic external outbound WAN internet traffic
    iptables -A IROH_ISOLATION -j DROP

    # Insert the custom chain at the very top of the OUTPUT chain for wlan0
    iptables -I OUTPUT 1 -o wlan0 -j IROH_ISOLATION

    echo "[*] Firewall applied successfully."
}

# Apply network isolation rules for both modes
apply_firewall

# Reverse-pairing dial-back (docs/usb-pairing.md): stage this phone's phone-*.addr
# payloads next to the deployment and, when the farm-agent binary is present,
# dial each phone node presenting the pairing token until it binds (paired files
# are renamed aside; 30s cadence for the first day, then hourly).
stage_phones() {
    dest="$1"
    count=0
    for f in "$USB_MOUNT"/phone-*.addr; do
        [ -f "$f" ] || continue
        cp "$f" "$dest/"
        count=$((count + 1))
    done
    echo "[*] Staged $count phone.addr file(s) in $dest"
}

# Write a self-contained retry runner next to the deployment so the dial-back
# survives reboots (hooked into start_app.sh in INSTALL mode, like firewall.sh).
write_pairing_runner() {
    dest="$1"
    runner="$dest/pairing.sh"
    echo "#!/bin/sh" > "$runner"
    echo "# Generated by flashforge_init.sh: dial-back retry loop (docs/usb-pairing.md)." >> "$runner"
    echo "D=\"$dest\"" >> "$runner"
    echo '[ -x "$D/farm-agent" ] || exit 0' >> "$runner"
    echo 'n=0' >> "$runner"
    echo 'while true; do' >> "$runner"
    echo '  for addr in "$D"/phone-*.addr; do' >> "$runner"
    echo '    [ -f "$addr" ] || continue' >> "$runner"
    echo '    if "$D/farm-agent" pair --phone-addr "$addr"; then' >> "$runner"
    echo '      mv "$addr" "$addr.paired" 2>/dev/null || true' >> "$runner"
    echo '    fi' >> "$runner"
    echo '  done' >> "$runner"
    echo '  remaining=$(ls "$D"/phone-*.addr 2>/dev/null | wc -l)' >> "$runner"
    echo '  [ "$remaining" -eq 0 ] && break' >> "$runner"
    echo '  n=$((n + 1))' >> "$runner"
    echo '  if [ "$n" -lt 2880 ]; then sleep 30; else sleep 3600; fi' >> "$runner"
    echo 'done' >> "$runner"
    chmod +x "$runner"
    echo "[*] Pairing runner written to $runner"
}

launch_pairing() {
    dest="$1"
    if [ -x "$dest/farm-agent" ] && ls "$dest"/phone-*.addr >/dev/null 2>&1; then
        "$dest/pairing.sh" &
        echo "[*] Dial-back agent launched in background."
    else
        echo "[*] farm-agent not present or no phone.addr staged; pairing dial-back inactive until the agent is deployed."
    fi
}

if [ "$MODE" = "INSTALL" ]; then
    echo "[*] Selected Mode: PERSISTENT STORAGE (INSTALL)"

    # 1. Create the persistent tracking directory
    mkdir -p "$IROH_PERSISTENT_DIR"

    # 2. Copy the ARMv7 Iroh binary and identity key, and set execution permissions
    cp "$IROH_BIN" "$IROH_PERSISTENT_DIR/iroh"
    chmod +x "$IROH_PERSISTENT_DIR/iroh"

    # 2b. Copy the dial-back agent when the provisioning phone shipped one
    if [ -f "$USB_MOUNT/farm-agent" ]; then
        cp "$USB_MOUNT/farm-agent" "$IROH_PERSISTENT_DIR/farm-agent"
        chmod +x "$IROH_PERSISTENT_DIR/farm-agent"
        echo "[*] farm-agent staged for pairing dial-back."
    fi

    if [ -f "$IROH_KEY" ]; then
        cp "$IROH_KEY" "$IROH_PERSISTENT_DIR/keypair.priv"
    else
        echo "[!] Warning: No identity key found at $IROH_KEY. Identity will be random."
    fi

    # 3. Ensure the vendor autostart script exists (create if necessary)
    if [ ! -f "$START_APP_SCRIPT" ]; then
        echo "[!] Warning: $START_APP_SCRIPT does not exist. Creating it."
        mkdir -p "$(dirname "$START_APP_SCRIPT")"
        touch "$START_APP_SCRIPT"
        chmod +x "$START_APP_SCRIPT"
    fi

    # Create a backup of the original start_app.sh if it doesn't already exist
    if [ ! -f "$START_APP_SCRIPT.backup" ]; then
        cp "$START_APP_SCRIPT" "$START_APP_SCRIPT.backup"
        echo "[*] Created backup of $START_APP_SCRIPT"
    fi

    # 4. Persist the firewall rules by creating a persistent firewall script
    FIREWALL_SCRIPT="$IROH_PERSISTENT_DIR/firewall.sh"
    echo "#!/bin/sh" > "$FIREWALL_SCRIPT"
    # Extract the body of apply_firewall to the script
    echo "iptables -D OUTPUT -o wlan0 -j IROH_ISOLATION 2>/dev/null || true" >> "$FIREWALL_SCRIPT"
    echo "iptables -F IROH_ISOLATION 2>/dev/null || true" >> "$FIREWALL_SCRIPT"
    echo "iptables -X IROH_ISOLATION 2>/dev/null || true" >> "$FIREWALL_SCRIPT"
    echo "iptables -N IROH_ISOLATION" >> "$FIREWALL_SCRIPT"
    echo "iptables -A IROH_ISOLATION -d 192.168.0.0/16 -j ACCEPT" >> "$FIREWALL_SCRIPT"
    echo "iptables -A IROH_ISOLATION -d 10.0.0.0/8 -j ACCEPT" >> "$FIREWALL_SCRIPT"
    echo "iptables -A IROH_ISOLATION -p udp --dport 53 -j ACCEPT" >> "$FIREWALL_SCRIPT"
    echo "iptables -A IROH_ISOLATION -p udp --dport 443 -j ACCEPT" >> "$FIREWALL_SCRIPT"
    echo "iptables -A IROH_ISOLATION -p tcp --dport 443 -j ACCEPT" >> "$FIREWALL_SCRIPT"
    echo "iptables -A IROH_ISOLATION -p tcp -j DROP" >> "$FIREWALL_SCRIPT"
    echo "iptables -A IROH_ISOLATION -j DROP" >> "$FIREWALL_SCRIPT"
    echo "iptables -I OUTPUT 1 -o wlan0 -j IROH_ISOLATION" >> "$FIREWALL_SCRIPT"
    chmod +x "$FIREWALL_SCRIPT"

    # 5. Append the execution hooks directly to the bottom of the start script if not present
    if ! grep -qF "$FIREWALL_SCRIPT" "$START_APP_SCRIPT"; then
        echo "" >> "$START_APP_SCRIPT"
        echo "$FIREWALL_SCRIPT" >> "$START_APP_SCRIPT"
        echo "[*] Autostart firewall hook appended to $START_APP_SCRIPT"
    fi

    if ! grep -qF "$START_COMMAND" "$START_APP_SCRIPT"; then
        echo "$START_COMMAND" >> "$START_APP_SCRIPT"
        echo "[*] Autostart node hook appended to $START_APP_SCRIPT"
    else
        echo "[*] Autostart hooks already exist in $START_APP_SCRIPT"
    fi

    # 5. Execute the Iroh node daemon for the current session
    echo "[*] Launching Iroh daemon..."
    eval "$START_COMMAND"

    # 6. Stage pairing payloads, persist the retry runner, hook it for reboot
    stage_phones "$IROH_PERSISTENT_DIR"
    write_pairing_runner "$IROH_PERSISTENT_DIR"
    PAIRING_HOOK="$IROH_PERSISTENT_DIR/pairing.sh"
    if ! grep -qF "$PAIRING_HOOK" "$START_APP_SCRIPT"; then
        echo "$PAIRING_HOOK &" >> "$START_APP_SCRIPT"
        echo "[*] Autostart pairing hook appended to $START_APP_SCRIPT"
    fi
    launch_pairing "$IROH_PERSISTENT_DIR"

else
    echo "[*] Selected Mode: RAM (Volatile Memory)"

    # 1. Copy binary directly to volatile memory (/tmp) to ensure a zero footprint on reboot
    cp "$IROH_BIN" /tmp/iroh
    if [ -f "$USB_MOUNT/farm-agent" ]; then
        cp "$USB_MOUNT/farm-agent" /tmp/farm-agent
    fi

    if [ -f "$IROH_KEY" ]; then
        cp "$IROH_KEY" /tmp/keypair.priv
    fi

    # 2. Set execution permissions
    chmod +x /tmp/iroh
    [ -f /tmp/farm-agent ] && chmod +x /tmp/farm-agent

    # 3. Launch the P2P daemon strictly in volatile memory
    echo "[*] Launching Iroh daemon in /tmp..."
    # The config-path points to /tmp to pick up the keypair.priv file
    /tmp/iroh node start --config-path=/tmp/ &

    # 4. Stage pairing payloads + start dial-back when the agent exists (no
    # reboot hook: RAM mode is zero-footprint by design)
    stage_phones "/tmp"
    write_pairing_runner "/tmp"
    launch_pairing "/tmp"
fi

echo "[*] Deployment fully complete."
exit 0
