#!/usr/bin/env python3
"""One-way foreign-slicer -> PrusaSlicer 3.0 profile converter.

Converts a profile from OrcaSlicer / Bambu Studio / SuperSlicer / Slic3r /
legacy PrusaSlicer into native PrusaSlicer 3.0 INI. Uses the translation table
generated by gen_dialect_key_map.py (dialect_key_map.json) as its single source
of truth; it performs no slicing and never touches the engine.

Usage:
  convert_to_prusa.py ORCA.json --dialect orca --out out.ini
  convert_to_prusa.py --dialect auto --dir /path/to/profiles --out-dir out/
  convert_to_prusa.py legacy.ini --dialect superslicer --out out.ini

JSON inheritance is resolved against a catalog built from --dir (or --base-dir)
when converting a directory, mirroring IOUtils.downloadProfilesRecursively but
filesystem-only. Single files with an unresolvable `inherits` produce a warning.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

JSON_DIALECTS = {"orca", "bambu"}
INI_DIALECTS = {"prusaslicer", "slic3r", "superslicer"}
DIALECTS = JSON_DIALECTS | INI_DIALECTS

# Converter-side transforms for keys flagged `type_changed` with a `transform`.
TRANSFORMS = {
    # Orca support_type ("normal"/"tree(auto)"/...) -> Prusa support_style enum.
    "support_type": lambda v: [("support_style", "organic" if "tree" in v.lower() or "organic" in v.lower() else "snug")],
}


def load_map(map_path: Path) -> dict:
    doc = json.loads(map_path.read_text())
    assert doc["schema"] == "dialect_profile_key_map", "unknown map schema"
    return doc


# --- source value serialization (mirrors IOUtils.configJsonToString) ----------
def jvalue_to_str(obj) -> str:
    if isinstance(obj, list):
        return ",".join(str(x) for x in obj)
    if isinstance(obj, bool):
        return "1" if obj else "0"
    if isinstance(obj, (int, float)):
        return str(obj)
    return str(obj)


def read_json_profile(path: Path) -> dict:
    return json.loads(path.read_text())


def read_ini_profile(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw in path.read_text(errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            continue  # section header; entries flattened
        if "=" in line:
            k, _, v = line.partition("=")
            out[k.strip()] = v.strip().replace("\\n", "\n")
    return out


def detect_format(path: Path) -> str:
    head = path.read_text(errors="replace").lstrip()
    # A JSON profile starts with '{'; everything else is treated as INI. The
    # dialect (orca / bambu / prusaslicer / slic3r / superslicer) is chosen
    # independently of the file format: an Orca-keyed *INI* (the app's own
    # stored ConfigObject.serialize() output) converts through the `orca`
    # dialect just like an Orca JSON vendor profile does.
    return "json" if head.startswith("{") else "ini"


# --- resolution / conversion --------------------------------------------------
def collect_flat(profile: dict, catalog: dict[str, dict], dialect: str) -> dict[str, str]:
    """Flatten a JSON profile, resolving `inherits` through `catalog` (name -> obj)."""
    flat: dict[str, str] = {}
    inherits = profile.get("inherits")
    if isinstance(inherits, str) and inherits:
        parent = catalog.get(inherits)
        if parent is not None:
            for k, v in collect_flat(parent, catalog, dialect).items():
                flat[k] = v
    for k, v in profile.items():
        if k in ("inherits", "name", "type", "print_settings_id",
                 "filament_settings_id", "printer_settings_id", "version"):
            continue
        flat[k] = jvalue_to_str(v)
    return flat


class ConvertStats:
    def __init__(self):
        self.renamed = 0   # key changed
        self.identity = 0  # key unchanged / not in table (passed through)
        self.removed = 0
        self.value_remapped = 0
        self.transformed = 0
        self.unmapped = 0  # key absent from the dialect table
        self.warnings: list[str] = []
        # Per-key disposition for --report auditing.
        self.renamed_keys: dict[str, str] = {}
        self.removed_keys: list[str] = []
        self.remapped_values: list[str] = []
        self.transformed_keys: list[str] = []
        self.unknown_keys: list[str] = []


def convert_entry(key: str, value: str, table: dict, dialect: str,
                  gcode_renames: dict, stats: ConvertStats) -> list[tuple[str, str]]:
    row = table.get(key)
    if row is None:
        stats.unmapped += 1
        stats.identity += 1
        stats.unknown_keys.append(key)
        return [(key, _rewrite_gcode(key, value, gcode_renames))]

    kind = row.get("kind", "rename")
    target = row.get("key")

    # type_changed with a transform runs first: it may legitimately have no
    # single target key (multi-key / value-only transforms).
    if kind == "type_changed" and row.get("transform"):
        fn = TRANSFORMS.get(row["transform"])
        if fn is None:
            stats.warnings.append(f"[{dialect}] {key}: unknown transform '{row['transform']}'; dropped")
            stats.removed += 1
            stats.removed_keys.append(key)
            return []
        stats.transformed += 1
        stats.transformed_keys.append(key)
        return [(k, v) for k, v in fn(value)]

    if kind == "removed" or target is None:
        stats.removed += 1
        stats.removed_keys.append(key)
        return []

    if target == key:
        stats.identity += 1
    else:
        stats.renamed += 1
        stats.renamed_keys[key] = target

    if row.get("values"):
        trimmed = value.strip()
        mapped = row["values"].get(trimmed)
        if mapped is None:
            stats.warnings.append(
                f"[{dialect}] {key}: enum value '{trimmed}' not in map, passed through unremapped")
            return [(target, _rewrite_gcode(key, value, gcode_renames))]
        stats.value_remapped += 1
        stats.remapped_values.append(key)
        return [(target, mapped)]

    return [(target, _rewrite_gcode(key, value, gcode_renames))]


def _rewrite_gcode(key: str, value: str, gcode_renames: dict) -> str:
    if key.endswith("_gcode") and "[" in value:
        for src, dst in gcode_renames.items():
            value = value.replace(f"[{src}]", f"{{{dst}[0]}}")
            value = value.replace(f"{src}", f"{dst}")
    return value


def convert(entries: dict[str, str], table: dict, dialect: str, gcode_renames: dict) -> tuple[dict[str, str], ConvertStats]:
    stats = ConvertStats()
    out: dict[str, str] = {}
    for k, v in entries.items():
        for tk, tv in convert_entry(k, v, table, dialect, gcode_renames, stats):
            out[tk] = tv
    return out, stats


def emit_ini(entries: dict[str, str], source_name: str) -> str:
    lines = [f"# converted to PrusaSlicer 3.0 by flashforge-farm from {source_name}", ""]
    for k in sorted(entries):
        v = entries[k].replace("\n", "\\n")
        lines.append(f"{k} = {v}")
    return "\n".join(lines) + "\n"


# --- CLI ----------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", nargs="*", type=Path, help="profile file(s) to convert")
    ap.add_argument("--dialect", choices=sorted(DIALECTS | {"auto"}), default="auto")
    ap.add_argument("--map", default=None, type=Path, help="dialect_key_map.json (default: app assets)")
    ap.add_argument("--dir", type=Path, default=None, help="convert all profiles under a directory")
    ap.add_argument("--out-dir", type=Path, default=None, help="output directory for --dir mode")
    ap.add_argument("--out", type=Path, default=None, help="output file for single-file mode")
    ap.add_argument("--base-dir", type=Path, default=None, help="extra dir scanned into the inheritance catalog")
    ap.add_argument("--report", type=Path, default=None,
                    help="write a JSON audit report of every key's disposition (renamed/removed/unknown/...)")
    args = ap.parse_args()

    # Default map location (committed generated artifact).
    map_path = args.map
    if map_path is None:
        repo = Path(__file__).resolve().parents[1]
        map_path = repo / "app/src/main/assets/dialect_key_map.json"
    doc = load_map(map_path)
    dialects_table = doc["dialects"]
    gcode_renames = doc.get("gcode_placeholder_renames", {})

    # Gather input files.
    files: list[Path] = []
    if args.dir:
        files += sorted(args.dir.rglob("*.json")) + sorted(args.dir.rglob("*.ini"))
    files += [p for p in args.input if p.is_file()]
    if not files:
        ap.error("no input files (pass files or --dir)")

    # Build inheritance catalog from all JSON files (+ base-dir).
    catalog: dict[str, dict] = {}
    scan_dirs = [args.dir] if args.dir else []
    if args.base_dir:
        scan_dirs.append(args.base_dir)
    for d in scan_dirs:
        if d and d.is_dir():
            for p in d.rglob("*.json"):
                try:
                    obj = read_json_profile(p)
                except Exception as e:
                    print(f"WARN: unreadable JSON {p}: {e}", file=sys.stderr)
                    continue
                catalog[p.stem] = obj
                for idkey in ("name", "print_settings_id", "filament_settings_id", "printer_settings_id"):
                    if isinstance(obj.get(idkey), str):
                        catalog[obj[idkey]] = obj

    failures = 0
    report_entries: list[dict] = []
    for path in files:
        fmt = detect_format(path)
        if args.dialect == "auto":
            dialect = "orca" if fmt == "json" else "superslicer"
        else:
            dialect = args.dialect
        if dialect not in dialects_table:
            print(f"SKIP {path}: unknown dialect '{dialect}'", file=sys.stderr)
            failures += 1
            continue
        table = dialects_table[dialect]

        try:
            if fmt == "json":
                obj = read_json_profile(path)
                entries = collect_flat(obj, catalog, dialect)
            else:
                entries = read_ini_profile(path)
        except Exception as e:
            print(f"ERROR {path}: {e}", file=sys.stderr)
            failures += 1
            continue

        out, stats = convert(entries, table, dialect, gcode_renames)

        if args.dir and args.out_dir:
            out_dir = args.out_dir
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path = out_dir / (path.stem + ".ini")
        elif args.out:
            out_path = args.out
            out_path.parent.mkdir(parents=True, exist_ok=True)
        elif len(files) == 1:
            out_path = path.with_suffix(".ini")
            out_path.parent.mkdir(parents=True, exist_ok=True)
        else:
            out_path = None

        if out_path:
            out_path.write_text(emit_ini(out, path.name))

        print(f"[{dialect}] {path.name}: {len(entries)} keys -> "
              f"{len(out)} ({stats.renamed} renamed, {stats.value_remapped} value-remapped, "
              f"{stats.transformed} transformed, {stats.removed} removed, {stats.unmapped} unmapped)",
              file=sys.stderr)
        for w in stats.warnings:
            print(f"  WARN {w}", file=sys.stderr)
        if stats.unmapped:
            print(f"  NOTE {path.name}: {stats.unmapped} keys not in the '{dialect}' dialect map "
                  f"(passed through unchanged; verify against the 3.0 print_config_def)", file=sys.stderr)

        if args.report:
            report_entries.append({
                "file": str(path),
                "dialect": dialect,
                "counts": {
                    "renamed": stats.renamed,
                    "identity": stats.identity,
                    "removed": stats.removed,
                    "value_remapped": stats.value_remapped,
                    "transformed": stats.transformed,
                    "unmapped": stats.unmapped,
                },
                "renamed": dict(sorted(stats.renamed_keys.items())),
                "removed": sorted(stats.removed_keys),
                "remapped_values": sorted(stats.remapped_values),
                "transformed": sorted(stats.transformed_keys),
                "unknown": sorted(stats.unknown_keys),
            })

    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps({"files": report_entries}, indent=2, sort_keys=True) + "\n")
        print(f"report -> {args.report}", file=sys.stderr)

    return failures


if __name__ == "__main__":
    raise SystemExit(main())