#!/usr/bin/env bash
# scripts/publish-models.sh — build the deterministic sample-models archive for
# the on-demand model library and (optionally) publish it as a rolling GitHub
# release the app downloads from (ModelLibrary.java -> models-latest).
#
# The app ships NO bundled STLs (~18MB kept out of the APK). Instead
# FileMenu/ModelLibrary download individual models from the `models-latest`
# GitHub release, sha-verified against models/manifest.json (itself pinned on
# device via ModelLibrary.MANIFEST_SHA). Nothing in CI used to publish that
# release — this script + the publish-models CI job close that gap.
#
# Determinism: the .stl hashes in models/models-manifest.json are pinned; the
# archive sha256 must equal manifest.archive["models.zip"]. The zip is built
# with fixed timestamps + sorted entries + fixed attrs so the same input always
# produces the same bytes, keeping the pin stable across runs.
#
# Usage:
#   scripts/publish-models.sh            # verify determinism (fail on pin drift)
#   scripts/publish-models.sh --refresh  # rebuild archive + regen manifest
#                                        # (prints new MANIFEST_SHA to install)
#   scripts/publish-models.sh --publish  # verify AND push models-latest release
# Env:  GH_TOKEN (for --publish)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd)"
MODELS_DIR="$SCRIPT_DIR/../models"
cd "$MODELS_DIR"

PY="$(command -v python3 || command -v python)"
REFORMAT=${REFORMAT:-0}
PUBLISH=0
case "${1:-}" in
  --refresh) REFORMAT=1 ;;
  --publish) PUBLISH=1 ;;
  -h|--help)
    sed -n '2,12p' "$0"; exit 0 ;;
  "") ;;
  *) echo "unknown arg: $1" >&2; exit 2 ;;
esac

# Deterministic python: manifest must list stl hashes matching the files, the
# archive hash must match how the zip is (re)built here, and the JSON must be
# regenerated byte-stably (indent=1, same key order) so MANIFEST_SHA never
# churns after a --refresh with no content change.
"$PY" - "$REFORMAT" <<'PYEOF'
import hashlib, io, json, os, sys, zipfile

REFRESH = sys.argv[1] == "1"
MANIFEST = "models-manifest.json"
STLS = sorted(f for f in os.listdir(".") if f.endswith(".stl"))

m = json.load(open(MANIFEST))

def sha256(path_or_bytes):
    h = hashlib.sha256()
    if isinstance(path_or_bytes, bytes):
        h.update(path_or_bytes)
    else:
        with open(path_or_bytes, "rb") as f:
            for blk in iter(lambda: f.read(65536), b""):
                h.update(blk)
    return h.hexdigest()

def build_archive():
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for name in STLS:
            info = zipfile.ZipInfo(name, (1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            z.writestr(info, open(name, "rb").read())
    return out.getvalue()

# 1. per-file hashes must match the committed manifest (never auto-update)
for name in STLS:
    want = m["files"].get(name)
    if want is None:
        sys.exit(f"ERROR: {name} missing from {MANIFEST} files\n  (refreshing requires editing manifest by hand; add the entry)")
    got = sha256(name)
    if want != got:
        sys.exit(f"ERROR: {name} hash mismatch:\n  manifest {want}\ngot       {got}")

# 2. deterministic archive vs manifest.archive["models.zip"]
archive = build_archive()
got_zip = hashlib.sha256(archive).hexdigest()
want_zip = m["archive"]["models.zip"]
if got_zip != want_zip:
    if REFRESH:
        m["archive"]["models.zip"] = got_zip
    else:
        sys.exit(f"ERROR: models.zip hash mismatch (pin {want_zip}, rebuilt {got_zip}).\n"
                 f"  Run scripts/publish-models.sh --refresh to regenerate the manifest, then install\n"
                 f"  the printed MANIFEST_SHA into app/src/main/java/.../modelrepo/ModelLibrary.java.")
open("models.zip", "wb").write(archive)
print("models.zip built (%d bytes, sha %s)" % (len(archive), got_zip))

# 3. byte-stable manifest regen (same bytes as committed when no pin drift)
manifest_bytes = (json.dumps(m, indent=1) + "\n").encode("utf-8")
if not REFRESH:
    have = open(MANIFEST, "rb").read()
    if have != manifest_bytes:
        sys.exit(f"ERROR: {MANIFEST} is not in regenerated form (editor reformatted it).\n"
                 f"  Run scripts/publish-models.sh --refresh to normalize.")
    print(f"manifest verified: {MANIFEST} sha {hashlib.sha256(manifest_bytes).hexdigest()}")
else:
    open(MANIFEST, "wb").write(manifest_bytes)
    print(f"manifest regenerated: {MANIFEST}")
    print("NEW MANIFEST_SHA -> ", hashlib.sha256(manifest_bytes).hexdigest())
PYEOF

if [ "$PUBLISH" -eq 1 ]; then
    command -v gh >/dev/null 2>&1 || { echo "ERROR: gh CLI required for --publish" >&2; exit 1; }
    : "${GH_TOKEN:?GH_TOKEN required for --publish}"
    TAG="models-latest"
    OUT=/tmp/models-release
    rm -rf "$OUT"; mkdir -p "$OUT"
    cp models.zip models-manifest.json catalog.json README.md "$OUT/"
    SUM="$(sha256sum "$OUT/models.zip" | cut -d' ' -f1)"
    SHA="$(git -C "$SCRIPT_DIR/.." rev-parse --short=10 HEAD 2>/dev/null || echo local)"
    DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '{"commit":"%s","built_at":"%s","schema":1,"archive":{"models.zip":"%s"}}\n' \
      "$SHA" "$DATE" "$SUM" > "$OUT/publish-manifest.json"
    gh release delete "$TAG" --yes --cleanup-tag --repo "$(git -C "$SCRIPT_DIR/.." remote get-url origin | sed 's#.*github.com[:/]##;s#\.git$##')" 2>/dev/null || true
    gh release create "$TAG" "$OUT/models.zip" "$OUT/models-manifest.json" "$OUT/catalog.json" \
      --repo "$(git -C "$SCRIPT_DIR/.." remote get-url origin | sed 's#.*github.com[:/]##;s#\.git$##')" \
      --title "Sample models (latest)" \
      --notes "Rolling release of the sample STL library downloaded on demand by ModelLibrary. Re-published whenever models/ changes."
    echo "published models-latest (models.zip $SUM)"
fi